name: smiling_tailor
description: Welcome to our tailor-centric Custom Business Management System, where the dynamic fusion of ERP (Enterprise Resource Planning) and CRM (Customer Relationship Management) empowers your tailoring business like never before. Our feature-rich and user-friendly application has been meticulously crafted to streamline your operations effortlessly. With our cutting-edge system, you can easily manage and monitor essential elements of your business, including managers, vendors, inventory, and employees. Effortlessly process orders and witness the seamless flow of transaction history in real-time, ensuring airtight organization, enhanced efficiency, and complete control over your business processes. We take pride in presenting this exceptional software solution, developed in-house by our skilled team at Algoramming. Our commitment to quality and reliability ensures that every aspect of our system is fine-tuned to meet the specific needs of your tailoring business, setting you on a path to success with unparalleled ease.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 0.0.22+22

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  beamer: ^2.0.0-dev.0
  fetch_client: ^1.0.2
  file_picker: ^6.1.1
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  flutter_slidable: ^3.0.1
  flutter_svg: ^2.0.9
  flutter_typeahead: ^4.8.0
  google_fonts: ^6.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_ui: ^1.0.14
  http: ^1.1.2
  image_cropper: ^5.0.1
  image_picker: ^1.0.4
  intl: ^0.18.1
  logger: ^2.0.2+1
  msix: ^3.16.7
  package_info_plus: ^5.0.1
  path: ^1.8.3
  path_provider: ^2.1.1
  pdf: ^3.10.6
  pocketbase: ^0.16.0
  printing: ^5.11.1
  rotated_corner_decoration: ^2.1.0+1
  share_plus: ^7.2.1
  shared_preferences: ^2.2.2
  syncfusion_flutter_charts: ^23.2.6
  toggle_switch: ^2.1.0
  url_launcher: ^6.2.1

dev_dependencies:
  build_runner: ^2.4.7
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  flutter_native_splash: ^2.3.6
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

msix_config:
  display_name: Smiling Tailor
  app_installer: #<-- app installer configuration
    publish_folder_path: D:\Algoramming\Flutter-Projects\smiling_tailor\publish
    hours_between_update_checks: 0
    automatic_background_task: true
    update_blocks_activation: true
    show_prompt: true
    force_update_from_any_version: false
  publisher_display_name: Algoramming
  identity_name: com.algoramming.smilingtailor
  msix_version: 0.0.22.0
  logo_path: D:\Algoramming\Flutter-Projects\smiling_tailor\assets\icons\app-icon-1024x1024.png

flutter_launcher_icons:
  ios: true
  android: true
  image_path: "assets/icons/app-icon-1024x1024.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/app-icon-1024x1024.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/icons/app-icon-1024x1024.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/app-icon-1024x1024.png"
  # command: dart run flutter_launcher_icons:main

flutter_native_splash:
  color: "#ffffff"
  image: "assets/icons/splash-icon-384x384.png"
  android: true
  ios: true
  web: true
  # command: dart run flutter_native_splash:create

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/files/
    - assets/fonts/
    - assets/gifs/
    - assets/icons/
    - assets/images/
    - assets/json/
    - assets/riv/
    - assets/svgs/
    - assets/types/
  # fonts:
  #   - family: Nunito
  #     fonts:
  #       - asset: assets/fonts/Nunito-Regular.ttf
  #       - asset: assets/fonts/Nunito-Bold.ttf
  #         weight: 400
  #       - asset: assets/fonts/Nunito-BoldItalic.ttf
  #         weight: 400
  #       - asset: assets/fonts/Nunito-Italic.ttf
  #         style: italic
