name: smiling_tailor
description: Introducing our tailor-focused ERP management system - a powerful,
  user-friendly application designed to streamline your tailoring business. Add
  managers, vendors, inventory, and employees effortlessly. Seamlessly process
  orders and track transaction history in real-time. Stay organized, efficient,
  and in control with our comprehensive software solution. Proudly developed as
  an in-house product of Algoramming, ensuring quality and reliability in every
  aspect.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 0.0.8+8

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  beamer: ^1.5.5
  fetch_client: ^1.0.0
  file_picker: ^5.3.2
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  flutter_slidable: ^3.0.0
  flutter_svg: ^2.0.7
  google_fonts: ^4.0.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_ui: ^1.0.14
  http: ^0.13.6
  image_cropper: ^4.0.1
  image_picker: ^0.8.9
  intl: ^0.18.0
  logger: ^1.4.0
  msix: ^3.14.2
  package_info_plus: ^4.0.2
  path: ^1.8.3
  path_provider: ^2.0.15
  pdf: ^3.10.4
  pocketbase: ^0.10.1
  share_plus: ^7.0.2
  shared_preferences: ^2.1.2
  syncfusion_flutter_charts: ^21.2.10
  toggle_switch: ^2.1.0
  url_launcher: ^6.1.11

dev_dependencies:
  build_runner: ^2.4.5
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.3.1
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0

msix_config:
  display_name: Smiling Tailor
  app_installer: #<-- app installer configuration
    publish_folder_path: D:\Algoramming\Flutter-Projects\smiling_tailor\publish
    hours_between_update_checks: 0
    automatic_background_task: true
    update_blocks_activation: true
    show_prompt: true
    force_update_from_any_version: false
  publisher_display_name: Algoramming
  identity_name: com.algoramming.smilingtailor
  msix_version: 0.0.8.0
  logo_path: D:\Algoramming\Flutter-Projects\smiling_tailor\assets\icons\app-icon-1024x1024.png

flutter_launcher_icons:
  ios: true
  android: true
  image_path: "assets/icons/app-icon-1024x1024.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/app-icon-1024x1024.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/icons/app-icon-1024x1024.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/app-icon-1024x1024.png"
  # command: dart run flutter_launcher_icons:main
  
flutter_native_splash:
  color: "#ffffff"
  image: "assets/icons/splash-icon-384x384.png"
  android: true
  ios: true
  web: true
  # command: dart run flutter_native_splash:create

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/files/
    - assets/gifs/
    - assets/icons/
    - assets/images/
    - assets/json/
    - assets/riv/
    - assets/svgs/
    - assets/types/
